# seachspecsES.yaml for linked-swissbib
# search target ElasticSearch
# ###########




AllFields:
  UsedTypes:
    - bibliographicResource
    - document
  UsedIndex:
    - testsb
  query:
    bool:
      should:
        multi_match:
          type:
            - cross_fields #should be default
          operator:
            - and #should be default
          fields:
            - dct:title
            - rdau:publicationStatement
            - @type
            - dc:contributor.rdfs:label
            - dc:contributor.@type
            - rdau:noteOnResource
            - dct:bibliographicCitation
            - bibo:isbn13
            - bibo:isbn10
        nested:
          path:
            - dc:contributor
          query:
            multi_match:
              fields:
                - dc:contributor.foaf:firstName
                - dc:contributor.foaf:lastName
              type:
                - cross_fields #should be default
              operator:
                - and # should be default




Contributor:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
    nested:
      path:
        - dc:contributor
      query:
        multi_match:
          fields:
            - dc:contributor.foaf:firstName
            - dc:contributor.foaf:lastName
            - dc:contributor.rdfs:label
          type:
            - cross_fields #should be default
          operator:
            - and # should be default



