Hellooo

<div id="workWrapper">
    <div id="personAuthorImage">
        <img alt="Der Bibliothekar" src="../themes/linkedswissbib/images/JudithKuckart_DerBibliothekar.jpg">
    </div>
    <div id="workDescription">
        <div id="resultView">
            <h2> <?
                $results = $this->results->getResults();
                foreach ($results as $rdfDriver):
                    $title = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getTitle());endforeach;
                ?><?echo $title?>
            </h2>
        </div>
        Jahr: <?
        $results = $this->results->getResults();
        foreach ($results as $rdfDriver):
            $title = preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getContributor());endforeach;
        ?><?echo $title?>
        <br>
        <br>
        <p>
            Geboren: 28. August 1749, Frankfurt am Main
            <br>
            Gestorben; 22. März 1832, Weimar
        </p>
        <div id="personAccordion">
            <div id="accordion" class="panel-group" role="tablist" aria-multiselectable="true">
                <div id="holdings-details" class="panel panel-default">
                    <div id="heading-details" class="panel-heading" role="tab">
                        <h3 class="panel-title">
                            <a data-toggle="collapse" href="#collapse-details" aria-expanded="false">
                                <span>Mehr Details zu Johann Wolfgang von Goethe</span>
                            </a>
                        </h3>
                    </div>
                    <div id="collapse-details" class="panel-collapse collapse" level="1" role="tabpanel" aria-labelledby="heading-details">
                        <div class="list-group">
                            <div id="personDetailsLabel">Biografie:</div>
                            <div id="personDetails">Johann Wolfgang von Goethe (* 28. August 1749 in Frankfurt am Main als Johann Wolfgang Goethe; † 22. März 1832 in Weimar), geadelt 1782, gilt als einer der bedeutendsten Repräsentanten deutschsprachiger Dichtung. Goethe stammte aus einer angesehenen bürgerlichen Familie; sein Grossvater mütterlicherseits war als Stadtschultheiss höchster Beamter der Stadt Frankfurt, sein Vater Doktor der Rechte und kaiserlicher Rat. Er und seine Schwester Cornelia erfuhren eine aufwendige Ausbildung durch Hauslehrer. Dem Wunsch seines Vaters folgend studierte Goethe in Strassburg und Leipzig Rechtswissenschaft und war danach als Advokat in Wetzlar und Frankfurt tätig. Gleichzeitig drängten ihn Talent und Neigung zur Dichtkunst, die ihm mit dem Drama Götz von Berlichingen einen frühen Erfolg und Anerkennung in der literarischen Welt zuteilwerden liess.</div>
                            <div id="personMoreDetails">Drama, Deutsche Literatur, Schauspiel, Gedichte</div>
                            <div id="personMoreLabels">Genre/Kategorie:</div>
                            <div id="personMoreDetails">wilhelminische Ära, Romantik, Aufklärung</div>
                            <div id="personMoreLabels">Bewegung, Zeit, Ära:</div>
                            <div id="personMoreDetails">
                                Johann Wolfgang von Göthe
                                <br>
                                Wolfgang von Goethe
                                <br>
                                Wolfgang Goethe
                                <br>
                                Johann Wolfgang Goethe
                            </div>
                            <div id="personMoreLabels">Namensvarianten:</div>
                            <div id="personMoreDetails">
                                Elisabeth Goethe (Mutter)
                                <br>
                                Friedel Knolle (berufliche Beziehung)
                                <br>
                                Rolf Alpers (berufliche Beziehung)
                                <br>
                                Hermann Heinzel (berufliche Beziehung)
                                <br>
                            </div>
                            <div id="personMoreLabels">In Beziehung stehend:</div>
                            <div id="personMoreDetails">
                                VIAF - Virtual International Authority File
                                <br>
                                Wikipedia (Deutsch)
                                <br>
                            </div>
                            <div id="personMoreLabels">Quellen:</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?
$results = $this->results->getResults();
foreach ($results as $rdfDriver): ?>
    <div id="resultView">
        <p>
        <h4><?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getTitle()); ?></h4>
        <b>Verfasser, Beitragende:</b> &nbsp;<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getName()); ?><br />
        <!--                <b>Verfasser, Beitragende:</b> &nbsp;<?/*=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getFirstNameResources()); */?>
                <?/*=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getLastNameResources()); */?><br />-->
        <b>Ort, Verlag, Jahr:</b> &nbsp; <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getPublicationStatement()); ?><br />
        <b>Beschreibung:</b> &nbsp; <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getFormat()); ?><br />
        <b>Link Cover (ID):</b> &nbsp; <a rel="external" href="<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getCover()); ?>">
            <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getCover()); ?></a><br />
        <b>Link Cover (ISBN10):</b> &nbsp; <a rel="external" href="<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10()); ?>">
            <?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10()); ?></a><br />
        <img src="<?=  preg_replace(['/</','/>/'], ['&lt;','&gt;'], $rdfDriver->getISBN10()); ?>">
        </p>
        <br />
    </div>
<? endforeach;?>
<p>&nbsp;</p>
</div>